# This workflow is intended to check that in-tree build of the translator is
# healthy and all tests pass. It is used in pre-commits and nightly builds.
#
# Documentation for GitHub Actions:
# [workflow-syntax]: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# [context-and-expression-syntax]: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
name: In-tree build & tests

on:
    push:
    pull_request:
        branches:
            - main

env:
  LLVM_VERSION: 22

jobs:
  build_windows:
    name: Windows
    strategy:
      matrix:
        build_type: [Release]
      fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Checkout LLVM sources
        uses: actions/checkout@v5
        with:
          repository: llvm/llvm-project
          ref: main
          path: llvm-project
      - name:  Checkout the translator sources
        uses: actions/checkout@v5
        with:
          path: llvm-project\\llvm\\projects\\SPIRV-LLVM-Translator
      - name:  Get tag for SPIR-V Headers
        id: spirv-headers-tag
        run: |
          echo "spirv_headers_tag=$(type llvm-project\\llvm\\projects\\SPIRV-LLVM-Translator\\spirv-headers-tag.conf)" >> $GITHUB_ENV
      - name:  Checkout SPIR-V Headers
        uses: actions/checkout@v5
        with:
          repository: KhronosGroup/SPIRV-Headers
          ref: ${{ env.spirv_headers_tag }}
          path: llvm-project\\llvm\\projects\\SPIRV-Headers
      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          cmake ..\\llvm-project\\llvm \
            -Thost=x64 \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_TARGETS_TO_BUILD="X86" \
            -DSPIRV_SKIP_CLANG_BUILD=ON \
            -DSPIRV_SKIP_DEBUG_INFO_TESTS=ON \
            -DLLVM_LIT_ARGS="-sv --no-progress-bar"
      - name: Build
        shell: bash
        run: |
          cd build
          cmake --build . --config ${{ matrix.build_type }} --target llvm-spirv --parallel